module.exports = {
  SAVED_PROJECT_RECEIVED: 'SAVED_PROJECT_RECEIVED',
  SAVED_PROJECT_REMOVED: 'SAVED_PROJECT_REMOVED',
  SAVED_PROJECT_UPDATED: 'SAVED_PROJECT_UPDATED',
  SAVED_PROJECTS_RECEIVED: 'SAVED_PROJECTS_RECEIVED'
};
